### PR TITLE
328 -> 142 Add-resource endpoint implemented

### PR DESCRIPTION
**Pull request by EAltunoglu**
Issue: #328. add-resource endpoint implemented. Unit tests are also implented for the endpoint.
Example Request Body:
{
    "path_id":  "61b864fffc7b6ca95de23214",
    "milestone_id": "61d1e3ec2377c51a4b99b149",
    "task_id": "61d1e3ec2377c51a4b99b149",
    "link": "http://bounswe11.com.s3-website.us-east-2.amazonaws.com/",
    "photo": ""
}
Example Response Body:
SUCCESS

### CODE REVIEW

**Review by myasins — APPROVED** [review]
Tests and the endpoint run successfully on my local, too. Simple and flawless.

**Comment by SelmanB** [comment]
Issue #142 about the testcases should be linked.

**Comment by SelmanB** [comment]
The conflicts are caused by the recent merge #358. Two distinct endpoints have similar functionality and therefore are seen as conflicts. Two authors of the two classes (@EAltunoglu @myasins ) should be resolving this new conflict.

**Comment by EAltunoglu** [comment]
Conflict is resolved.

**Pull request merged**
