### PR TITLE
backend-master <- 227

### PR DESCRIPTION
**Pull request by myasins**
Enroll path and unenroll path endpoints are added separately. Local tests are done and results are posted on #227. We created another collection to keep the data of username who enrolls and id of path which is enrolled, in our MongoDB server.

### CODE REVIEW

**Review by EAltunoglu — APPROVED** [review]
I reviewed the code. It seems perfect. I tested endpoint on my local. It works as expected. To me, HTTP 400 should be returned in case of missing request body. But it can be added later.

**Review by SelmanB — APPROVED** [review]
The changes all make sense and are tested

**Comment by SelmanB** [comment]
Conflicts are resolved to include the new states that are tested

**Comment by SelmanB** [comment]
Conflicts resolved to include the newer version that was tested. Changes to the old code is found to be benign.

**Pull request merged**
