### PR TITLE
Android Search Feature

### PR DESCRIPTION
**Pull request by Hazerank**
The search feature for the android application is implemented nearly fully. It is decided to allocate explore page for search feature and all search related operations should be done under there. In this manner, the improvements done in the pull request is as follows:
- Main page is cleared from search bar features and search future migrated to the explore page
- The search path http request is implemented.
- The search user http request is implemented.
- User Container and Tag Container are implemented.
- The design of the search page is done as similar to home page.
- Search feature is done basically.

### CODE REVIEW

**Comment by fihlie** [comment]
You can also try futures for parallel search, otherwise thanks for implementing search this will make things easier for users. You are the best

**Review by fihlie — APPROVED** [review]
As I commented before, thanks I couldn't see any problems we can merge after Kürşat's approval

**Review by kursatbakis — APPROVED** [review]
As a suggestion, you can change the icon for search tab. Good coding and glad you are following the standards.

**Comment by Hazerank** [comment]
Thanks for your valuable feedbacks !

**Pull request merged**
