### PR TITLE
Fe/edit profile

### LINKED ISSUE #238: Edit Profile
Using the API https://github.com/bounswe/2021SpringGroup11/wiki/API-Endpoint-Definitions#edit-user-useredit-user-post, Users can edit their Username, Email, First Name, Last Name, Bio, Photo

Deadline: December 12, 2021

### PR DESCRIPTION
**Pull request by emindeniz99**
Using the API https://github.com/bounswe/2021SpringGroup11/wiki/API-Endpoint-Definitions#edit-user-useredit-user-post, Users can edit their Username, Email, First Name, Last Name, Bio, Photo

image
image
image
image

TODO: saving is not working, because auth token for axios does not work, it is separate issue from this feature.

close #238

### CODE REVIEW

**Comment by bekirtatar** [comment]
Screenshot_13
  I am getting this screen on my local at 1920*1080 resolution. Should I use another resolution or is this a size bug? If that's the case, You should fix it. @emindeniz99 
  
  The user I used:
robertdown
asd1234

**Comment by emindeniz99** [comment]
> Screenshot_13 I am getting this screen on my local at 1920*1080 resolution. Should I use another resolution or is this a size bug? If that's the case, You should fix it. @emindeniz99
> 
> The user I used: robertdown asd1234

I can not reproduce this issue, It works perfectly with the user credentials that you mentioned.

image
Browser: MS Edge (Chromium) Version 96.0.1054.41 (Official build) (arm64 Mac OS)

**Comment by bekirtatar** [comment]
> > Screenshot_13 I am getting this screen on my local at 1920*1080 resolution. Should I use another resolution or is this a size bug? If that's the case, You should fix it. @emindeniz99
> > The user I used: robertdown asd1234
> 
> I can not reproduce this issue, It works perfectly with the user credentials that you mentioned.
> 
> image Browser: MS Edge (Chromium) Version 96.0.1054.41 (Official build) (arm64 Mac OS)

I could not reproduce this issue again. It works fine now. I didn't understand why it was like that before. I am approving this now. If we get the same error again on the develop branch, we can open a bug issue about this.

**Review by bekirtatar — APPROVED** [review]
It works fine now. You can merge it.

**Pull request merged**
