### PR TITLE
stocksAPI added

### PR DESCRIPTION
**Pull request by bekirtatar**
I added stocks API to practice-app. 
- Deleted react files.
- Added the functionality of getting stock prices and commenting on them.
- Created a python program to initialize the database with some stock prices according to the given period.

### CODE REVIEW

**Review by emindeniz99 — CHANGES_REQUESTED** [review]

**Comment by emindeniz99** [comment]
I can not run it
image

**Comment by bekirtatar** [comment]
@emindeniz99 You should run the "py manage.py migrate" code before the run server. If you get the same error again, check your database settings and try to create a new local database with the name in the settings.

**Comment by bekirtatar** [comment]
@emindeniz99 If my code runs in your local without any errors, We can merge this to the master branch.

**Comment by emindeniz99** [comment]
> @emindeniz99 You should run the "py manage.py migrate" code before the run server. If you get the same error again, check your database settings and try to create a new local database with the name in the settings.

thank you, migration solved my problem. It works.

**Review by emindeniz99 — APPROVED** [review]

**Pull request merged**
