### PR TITLE
Wikidata endpoints determined & initial versions of features added

### PR DESCRIPTION
**Pull request by EAltunoglu**
There is an example request code for wikidata request. It will be deleted later. Additionally, example data for wikidata responses added.

### CODE REVIEW

**Comment by myasins** [comment]
We comprehended the endpoint request & response structures of Wikidata, which we will use in our backend side.

**Comment by SelmanB** [comment]
Comments including URLs for other versions of API calls may be relevant and better kept there as is done.

**Comment by SelmanB** [comment]
Temporary data fethced from wikidata is also added to git. I confirmed that they are not used. They should be removed. See #246

**Comment by SelmanB** [comment]
#246 is resolved.

**Comment by SelmanB** [comment]
Should we put the `code.py` file (the one that is changed by the commits above) elsewhere?

**Comment by EAltunoglu** [comment]
I will share code.py on Slack.

**Comment by SelmanB** [comment]
We found there is no problem for it to remain as long as it is shortly documented

**Review by SelmanB — APPROVED** [review]
All the changes requested and done are written in the comments

**Pull request merged**
