### PR TITLE
merge 323 into 326

### PR DESCRIPTION
**Pull request by SelmanB**
User-specific activity streams endpoint created as requested by issue #323.

### CODE REVIEW

**Comment by EAltunoglu** [comment]
Unit tests are missing.

**Comment by EAltunoglu** [comment]
This endpoint should use isAuthenticated middleware

**Comment by EAltunoglu** [comment]
print statements should be removed.

**Comment by SelmanB** [comment]
The requested changes are done in the [commit](https://github.com/bounswe/2021SpringGroup11/commit/fa620a561f2b34c53c3059ebceacfb16b8b2dd8c)

**Review by myasins — APPROVED** [review]
Runs issueless. Unit tests will be added later to make endpoint available to be used by other teams.

**Pull request merged**
