### PR TITLE
Merge 342

### PR DESCRIPTION
**Pull request by SelmanB**
Activity stream is implemented for `create-path` endpoint.

### CODE REVIEW

**Comment by SelmanB** [comment]
The resolved conflict was a mistake corrected later in branch 326. The version in 326 is accepted.

**Review by EAltunoglu — COMMENTED** [review]
act_id is added to code. But it is not used. Is it added for other branches?

**Comment by SelmanB** [comment]
It is not used but is in place in case it may be used in a future informative logger.

**Review by myasins — APPROVED** [review]
Changes are OK according to our decisions mentioned at #342.

**Review by EAltunoglu — APPROVED** [review]
A conflict is resolved. I tested feature on my local. Works fine.

**Pull request merged**
