### PR TITLE
add docker

### PR DESCRIPTION
**Pull request by emindeniz99**
- [x] dockerfile
- [x] docker-compose that includes django and postgresql

### CODE REVIEW

**Comment by emindeniz99** [comment]
Can you test with `docker-compose up`?

**Comment by fihlie** [comment]
image
I got this error

**Comment by emindeniz99** [comment]
> image
> I got this error

Could you run hello-world example of docker?

**Review by bekirtatar — COMMENTED** [review]
@emindeniz99 When I run the docker-compose up, the application works but the stocks API home page cannot be loaded.
When I start the server without docker, the application works perfectly fine. I don't understand why this is happening.

**Review by bekirtatar — APPROVED** [review]
It works fine now.

**Comment by emindeniz99** [comment]
close https://github.com/bounswe/2021SpringGroup11/issues/38

**Pull request merged**
